server:
  port: 8080
  servlet:
    context-path: /mj
logging:
  level:
    ROOT: info
    com.github.novicezk.midjourney: debug
knife4j:
  enable: true
  openapi:
    title: Midjourney Proxy API문서
    description: AI 그리기를 위한 API 호출을 구현하기 위해 MidJourney의 디스코드 채널 에이전트로 활동합니다.
    concat: novicezk
    url: https://github.com/novicezk/midjourney-proxy
    version: v2.6.3
    terms-of-service-url: https://github.com/novicezk/midjourney-proxy
    group:
      api:
        group-name: API
        api-rule: package
        api-rule-resources:
          - com.github.novicezk.midjourney.controller